[package]
name = "test-uintr"
version.workspace = true
edition.workspace = true

[dependencies]
uintr-runtime.workspace = true
libc.workspace = true

[build-dependencies]
cc = "1.0"

[[bin]]
name = "uintr-sender"
path = "src/bin/uintr_sender.rs"

[[bin]]
name = "uintr-receiver"
path = "src/bin/uintr_receiver.rs"
